

### register user

POST http://localhost:4400/user/register
Content-Type: application/json

{
  "Username": "john_doe",
  "Email": "john.doe@example.com",
  "PasswordHash": "12345678"
}


### register user


POST http://localhost:4400/user/register
Content-Type: application/json

{
  "Username": "Greewood Alex",
  "Email": "greenwood@gmail.com",
  "PasswordHash": "12345678"
}



### login 
POST http://localhost:4400/user/login
Content-Type: application/json

{
    "Email": "theuser@gmail.com",
    "PasswordHash": "12345678"
}

### login 
POST http://localhost:4400/user/login
Content-Type: application/json

{
    "Email": "crispinmanda@gmail.com",
    "PasswordHash": "12345678"
}



### fetching All users PROFILE

GET http://localhost:4400/user
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiJkNWU3NGM4ZS05NmZlLTRlYzUtOTIzMS0zOGZmMjhiMjBkYzYiLCJFbWFpbCI6ImNyaXNwaW5tYW5kYUBnbWFpbC5jb20iLCJQYXNzd29yZEhhc2giOiIkMmIkMDUkMmJmTjNoQ1dkVGRQNGlmUUJRMTBZdWxmbFZOOHlDWlFwR0tjdXAyOWh6blhvc1IzZ2NzaTIiLCJMYXN0TmFtZSI6bnVsbCwiRGF0ZU9mQmlydGgiOm51bGwsIlJlZ2lzdHJhdGlvbkRhdGUiOiIyMDIzLTEyLTA4VDExOjE5OjU0LjY2M1oiLCJQcm9maWxlUGljdHVyZVVybCI6bnVsbCwiV2Vic2l0ZSI6bnVsbCwiTG9jYXRpb24iOm51bGwsIklzVmVyaWZpZWQiOmZhbHNlLCJPdHBTZWNyZXQiOm51bGwsImlzV2VsY29tZWQiOnRydWUsImlhdCI6MTcwMjcyMjQ2NCwiZXhwIjoxNzAyODA4ODY0fQ.x9UKzt6kOz2QE3F2pBUFjuyQn8iJAPfU2iWi40WOLFM

### fetching one user
GET http://localhost:4400/user/1d98c619-e8fc-478f-93a1-d94117db1be1
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiJkNWU3NGM4ZS05NmZlLTRlYzUtOTIzMS0zOGZmMjhiMjBkYzYiLCJFbWFpbCI6ImNyaXNwaW5tYW5kYUBnbWFpbC5jb20iLCJQYXNzd29yZEhhc2giOiIkMmIkMDUkMmJmTjNoQ1dkVGRQNGlmUUJRMTBZdWxmbFZOOHlDWlFwR0tjdXAyOWh6blhvc1IzZ2NzaTIiLCJMYXN0TmFtZSI6bnVsbCwiRGF0ZU9mQmlydGgiOm51bGwsIlJlZ2lzdHJhdGlvbkRhdGUiOiIyMDIzLTEyLTA4VDExOjE5OjU0LjY2M1oiLCJQcm9maWxlUGljdHVyZVVybCI6bnVsbCwiV2Vic2l0ZSI6bnVsbCwiTG9jYXRpb24iOm51bGwsIklzVmVyaWZpZWQiOmZhbHNlLCJPdHBTZWNyZXQiOm51bGwsImlzV2VsY29tZWQiOnRydWUsImlhdCI6MTcwMjkxMDg4MywiZXhwIjoxNzAyOTk3MjgzfQ.85SEVhSeb9AXD8vmPdOThJswqVdsvygXZvFnX_vGgPY

####POST ROUTES

###Create Post
POST http://localhost:4400/post/create
Content-Type: application/json

{
 "UserId":"1d98c619-e8fc-478f-93a1-d94117db1be1",
  "Content": "Intergration Review"
  
}


####Get All Posts

GET http://localhost:4400/post/Allposts
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiJkNWU3NGM4ZS05NmZlLTRlYzUtOTIzMS0zOGZmMjhiMjBkYzYiLCJFbWFpbCI6ImNyaXNwaW5tYW5kYUBnbWFpbC5jb20iLCJQYXNzd29yZEhhc2giOiIkMmIkMDUkMmJmTjNoQ1dkVGRQNGlmUUJRMTBZdWxmbFZOOHlDWlFwR0tjdXAyOWh6blhvc1IzZ2NzaTIiLCJMYXN0TmFtZSI6bnVsbCwiRGF0ZU9mQmlydGgiOm51bGwsIlJlZ2lzdHJhdGlvbkRhdGUiOiIyMDIzLTEyLTA4VDExOjE5OjU0LjY2M1oiLCJQcm9maWxlUGljdHVyZVVybCI6bnVsbCwiV2Vic2l0ZSI6bnVsbCwiTG9jYXRpb24iOm51bGwsIklzVmVyaWZpZWQiOmZhbHNlLCJPdHBTZWNyZXQiOm51bGwsImlzV2VsY29tZWQiOnRydWUsImlhdCI6MTcwMjkxNjk2MCwiZXhwIjoxNzAzMDAzMzYwfQ.USWOYaKpE7czVR7_BT5D2cdW3f2aBtKq3opsztWFPGw



###Create comment
POST http://localhost:4400/post/createcomment
Content-Type: application/json

{
  "Content": "hello WORLD.",
  "UserId": "1d98c619-e8fc-478f-93a1-d94117db1be1" ,  
  "PostId": "2de85919-adc1-4560-85dd-cd82aa951e87"      
}



### All comment

GET http://localhost:4400/post/allcomments
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiJkNWU3NGM4ZS05NmZlLTRlYzUtOTIzMS0zOGZmMjhiMjBkYzYiLCJFbWFpbCI6ImNyaXNwaW5tYW5kYUBnbWFpbC5jb20iLCJQYXNzd29yZEhhc2giOiIkMmIkMDUkMmJmTjNoQ1dkVGRQNGlmUUJRMTBZdWxmbFZOOHlDWlFwR0tjdXAyOWh6blhvc1IzZ2NzaTIiLCJMYXN0TmFtZSI6bnVsbCwiRGF0ZU9mQmlydGgiOm51bGwsIlJlZ2lzdHJhdGlvbkRhdGUiOiIyMDIzLTEyLTA4VDExOjE5OjU0LjY2M1oiLCJQcm9maWxlUGljdHVyZVVybCI6bnVsbCwiV2Vic2l0ZSI6bnVsbCwiTG9jYXRpb24iOm51bGwsIklzVmVyaWZpZWQiOmZhbHNlLCJPdHBTZWNyZXQiOm51bGwsImlzV2VsY29tZWQiOnRydWUsImlhdCI6MTcwMjkzMjA2OCwiZXhwIjoxNzAzMDE4NDY4fQ.YxfS_zJBoIHGZOB6Pdx8XGoOK9Cb0F1pAtgFyiSVgDc


###Edit Comment
PUT http://localhost:4400/post/updatecomment
Content-Type: application/json

{
    "PostId":"2de85919-adc1-4560-85dd-cd82aa951e87",
    "UserId": "22a57df2-7653-4c60-998d-5dd23580df21",
    "Content": "Not today try next week",
    "CommentId": "2442837b-be91-4a70-9078-e7fc71d17524"
}



### Follow

POST  http://localhost:4400/user/Follow/659237ec-abb6-4b1a-ba4b-5544d14cea06
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2M2U1MzNiMy00NjZkLTQ0ZmEtYWE3Yi0wOWU5MmZjMWFlYzAiLCJFbWFpbCI6InRoZXVzZXJAZ21haWwuY29tIiwiUGFzc3dvcmRIYXNoIjoiJDJiJDA1JDRQMUZwaG5aY0JYRzVEZC9YLkQ4YmV4Lnl6OXZzbDB5bWliMmsxT3g1SVBYRURKNWsySVk2IiwiTGFzdE5hbWUiOm51bGwsIkRhdGVPZkJpcnRoIjpudWxsLCJSZWdpc3RyYXRpb25EYXRlIjoiMjAyMy0xMi0xNVQxMjozODoxOC45NzNaIiwiUHJvZmlsZVBpY3R1cmVVcmwiOm51bGwsIldlYnNpdGUiOm51bGwsIkxvY2F0aW9uIjpudWxsLCJJc1ZlcmlmaWVkIjpmYWxzZSwiT3RwU2VjcmV0IjpudWxsLCJpc1dlbGNvbWVkIjp0cnVlLCJpYXQiOjE3MDI3NDE3ODgsImV4cCI6MTcwMjgyODE4OH0.J44GMBr3H29LK6c4nJq8pvtZHW6AEgz455cjq5Faixg

{
  "FollowerUserId": "22a57df2-7653-4c60-998d-5dd23580df21",
  "FollowingUserId": "659237ec-abb6-4b1a-ba4b-5544d14cea06"
}




###like and unlike post

POST http://localhost:4400/post/likepost
Content-Type: application/json

{
  "UserId":"22a57df2-7653-4c60-998d-5dd23580df21", 
  "PostId":"2de85919-adc1-4560-85dd-cd82aa951e87"
}



###FOLLOW AND UNFOLLOW USERS
POST http://localhost:4400/user/toggleFollowUser
Content-Type: application/json

{
   "followingUserId":"1ba73919-bf2f-42ab-9219-295f35fd7873", 
   "followedUserId":"22a57df2-7653-4c60-998d-5dd23580df21"
}


### GET FOLLOWINGS
GET http://localhost:4400/user/getFollowings/1ba73919-bf2f-42ab-9219-295f35fd7873
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2M2U1MzNiMy00NjZkLTQ0ZmEtYWE3Yi0wOWU5MmZjMWFlYzAiLCJFbWFpbCI6InRoZXVzZXJAZ21haWwuY29tIiwiUGFzc3dvcmRIYXNoIjoiJDJiJDA1JDRQMUZwaG5aY0JYRzVEZC9YLkQ4YmV4Lnl6OXZzbDB5bWliMmsxT3g1SVBYRURKNWsySVk2IiwiTGFzdE5hbWUiOm51bGwsIkRhdGVPZkJpcnRoIjpudWxsLCJSZWdpc3RyYXRpb25EYXRlIjoiMjAyMy0xMi0xNVQxMjozODoxOC45NzNaIiwiUHJvZmlsZVBpY3R1cmVVcmwiOm51bGwsIldlYnNpdGUiOm51bGwsIkxvY2F0aW9uIjpudWxsLCJJc1ZlcmlmaWVkIjpmYWxzZSwiT3RwU2VjcmV0IjpudWxsLCJpc1dlbGNvbWVkIjp0cnVlLCJpYXQiOjE3MDI3NDc2MDksImV4cCI6MTcwMjgzNDAwOX0.VzHvNNI-F6cIsl25KdgvqCasaeb_yYedDApGYyPlISc
