

### register user

POST http://localhost:4400/user/register
Content-Type: application/json

{
  "Username": "john_doe",
  "Email": "john.doe@example.com",
  "PasswordHash": "12345678"
}


### register user

POST http://localhost:4400/user/register
Content-Type: application/json

{
  "Username": "The User",
  "Email": "theuser@gmail.com",
  "PasswordHash": "12345678"
}



### login 
POST http://localhost:4400/user/login
Content-Type: application/json

{
    "Email": "theuser@gmail.com",
    "PasswordHash": "12345678"
}

### login 
POST http://localhost:4400/user/login
Content-Type: application/json

{
    "Email": "crispinmanda@gmail.com",
    "PasswordHash": "12345678"
}



### fetching users PROFILE
GET http://localhost:4400/user
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiJkNWU3NGM4ZS05NmZlLTRlYzUtOTIzMS0zOGZmMjhiMjBkYzYiLCJFbWFpbCI6ImNyaXNwaW5tYW5kYUBnbWFpbC5jb20iLCJQYXNzd29yZEhhc2giOiIkMmIkMDUkMmJmTjNoQ1dkVGRQNGlmUUJRMTBZdWxmbFZOOHlDWlFwR0tjdXAyOWh6blhvc1IzZ2NzaTIiLCJMYXN0TmFtZSI6bnVsbCwiRGF0ZU9mQmlydGgiOm51bGwsIlJlZ2lzdHJhdGlvbkRhdGUiOiIyMDIzLTEyLTA4VDExOjE5OjU0LjY2M1oiLCJQcm9maWxlUGljdHVyZVVybCI6bnVsbCwiV2Vic2l0ZSI6bnVsbCwiTG9jYXRpb24iOm51bGwsIklzVmVyaWZpZWQiOmZhbHNlLCJPdHBTZWNyZXQiOm51bGwsImlhdCI6MTcwMjU2MzA2NCwiZXhwIjoxNzAyNjQ5NDY0fQ.09KKerGC01HZo1MvUGnQJSEEctFsHSIII6rmEuCmUXI

### fetching one user
GET http://localhost:4400/user/1d98c619-e8fc-478f-93a1-d94117db1be1
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI2M2U1MzNiMy00NjZkLTQ0ZmEtYWE3Yi0wOWU5MmZjMWFlYzAiLCJFbWFpbCI6InRoZXVzZXJAZ21haWwuY29tIiwiUGFzc3dvcmRIYXNoIjoiJDJiJDA1JDRQMUZwaG5aY0JYRzVEZC9YLkQ4YmV4Lnl6OXZzbDB5bWliMmsxT3g1SVBYRURKNWsySVk2IiwiTGFzdE5hbWUiOm51bGwsIkRhdGVPZkJpcnRoIjpudWxsLCJSZWdpc3RyYXRpb25EYXRlIjoiMjAyMy0xMi0xNVQxMjozODoxOC45NzNaIiwiUHJvZmlsZVBpY3R1cmVVcmwiOm51bGwsIldlYnNpdGUiOm51bGwsIkxvY2F0aW9uIjpudWxsLCJJc1ZlcmlmaWVkIjpmYWxzZSwiT3RwU2VjcmV0IjpudWxsLCJpYXQiOjE3MDI2MzMxOTUsImV4cCI6MTcwMjcxOTU5NX0.3msnngJYwTtg7TYCoZMVoxVLHjBw2V5NYeWRZgrnY9c


####POST ROUTES

###Create Post
POST http://localhost:4400/post/create
Content-Type: application/json

{
 "UserId":"1d98c619-e8fc-478f-93a1-d94117db1be1",
  "Content": "This is the content of the new user"
  
}

####Get All Posts

GET http://localhost:4400/post/Allposts


###Create comment
POST http://localhost:4400/post/createcomment
Content-Type: application/json

{
  "Content": "This is a another comment for you.",
  "UserId": "1d98c619-e8fc-478f-93a1-d94117db1be1" ,  
  "PostId": "2de85919-adc1-4560-85dd-cd82aa951e87"      
}



### All comment

GET http://localhost:4400/post/allcomments
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiJkNWU3NGM4ZS05NmZlLTRlYzUtOTIzMS0zOGZmMjhiMjBkYzYiLCJFbWFpbCI6ImNyaXNwaW5tYW5kYUBnbWFpbC5jb20iLCJQYXNzd29yZEhhc2giOiIkMmIkMDUkMmJmTjNoQ1dkVGRQNGlmUUJRMTBZdWxmbFZOOHlDWlFwR0tjdXAyOWh6blhvc1IzZ2NzaTIiLCJMYXN0TmFtZSI6bnVsbCwiRGF0ZU9mQmlydGgiOm51bGwsIlJlZ2lzdHJhdGlvbkRhdGUiOiIyMDIzLTEyLTA4VDExOjE5OjU0LjY2M1oiLCJQcm9maWxlUGljdHVyZVVybCI6bnVsbCwiV2Vic2l0ZSI6bnVsbCwiTG9jYXRpb24iOm51bGwsIklzVmVyaWZpZWQiOmZhbHNlLCJPdHBTZWNyZXQiOm51bGwsImlhdCI6MTcwMjU3NjIzMiwiZXhwIjoxNzAyNjYyNjMyfQ.GyxcbYuXWeDem1_WMu69NRRAttcKrRUTCTgCdAfIAqg


###Edit Comment
PUT http://localhost:4400/post/updatecomment
Content-Type: application/json

{
    "PostId":"2de85919-adc1-4560-85dd-cd82aa951e87",
    "UserId": "22a57df2-7653-4c60-998d-5dd23580df21",
    "Content": "Not today try next week",
    "CommentId": "2442837b-be91-4a70-9078-e7fc71d17524"
}





### Likes

PUT  http://localhost:4400/user/2de85919-adc1-4560-85dd-cd82aa951e87/like
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiJkNWU3NGM4ZS05NmZlLTRlYzUtOTIzMS0zOGZmMjhiMjBkYzYiLCJFbWFpbCI6ImNyaXNwaW5tYW5kYUBnbWFpbC5jb20iLCJQYXNzd29yZEhhc2giOiIkMmIkMDUkMmJmTjNoQ1dkVGRQNGlmUUJRMTBZdWxmbFZOOHlDWlFwR0tjdXAyOWh6blhvc1IzZ2NzaTIiLCJMYXN0TmFtZSI6bnVsbCwiRGF0ZU9mQmlydGgiOm51bGwsIlJlZ2lzdHJhdGlvbkRhdGUiOiIyMDIzLTEyLTA4VDExOjE5OjU0LjY2M1oiLCJQcm9maWxlUGljdHVyZVVybCI6bnVsbCwiV2Vic2l0ZSI6bnVsbCwiTG9jYXRpb24iOm51bGwsIklzVmVyaWZpZWQiOmZhbHNlLCJPdHBTZWNyZXQiOm51bGwsImlhdCI6MTcwMjU3NjIzMiwiZXhwIjoxNzAyNjYyNjMyfQ.GyxcbYuXWeDem1_WMu69NRRAttcKrRUTCTgCdAfIAqg

{
  "PostId": "2de85919-adc1-4560-85dd-cd82aa951e87" ,
  "UserId": "22a57df2-7653-4c60-998d-5dd23580df21"  
     
}


### Follow

POST  http://localhost:4400/user/Follow/659237ec-abb6-4b1a-ba4b-5544d14cea06
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiJkNWU3NGM4ZS05NmZlLTRlYzUtOTIzMS0zOGZmMjhiMjBkYzYiLCJFbWFpbCI6ImNyaXNwaW5tYW5kYUBnbWFpbC5jb20iLCJQYXNzd29yZEhhc2giOiIkMmIkMDUkMmJmTjNoQ1dkVGRQNGlmUUJRMTBZdWxmbFZOOHlDWlFwR0tjdXAyOWh6blhvc1IzZ2NzaTIiLCJMYXN0TmFtZSI6bnVsbCwiRGF0ZU9mQmlydGgiOm51bGwsIlJlZ2lzdHJhdGlvbkRhdGUiOiIyMDIzLTEyLTA4VDExOjE5OjU0LjY2M1oiLCJQcm9maWxlUGljdHVyZVVybCI6bnVsbCwiV2Vic2l0ZSI6bnVsbCwiTG9jYXRpb24iOm51bGwsIklzVmVyaWZpZWQiOmZhbHNlLCJPdHBTZWNyZXQiOm51bGwsImlhdCI6MTcwMjU3NjIzMiwiZXhwIjoxNzAyNjYyNjMyfQ.GyxcbYuXWeDem1_WMu69NRRAttcKrRUTCTgCdAfIAqg

{
  "FollowerUserId": "22a57df2-7653-4c60-998d-5dd23580df21",
  "FollowingUserId": "659237ec-abb6-4b1a-ba4b-5544d14cea06"
}



### getAllFollowers

GET  http://localhost:4400/user/getAllFollowers/
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiJkNWU3NGM4ZS05NmZlLTRlYzUtOTIzMS0zOGZmMjhiMjBkYzYiLCJFbWFpbCI6ImNyaXNwaW5tYW5kYUBnbWFpbC5jb20iLCJQYXNzd29yZEhhc2giOiIkMmIkMDUkMmJmTjNoQ1dkVGRQNGlmUUJRMTBZdWxmbFZOOHlDWlFwR0tjdXAyOWh6blhvc1IzZ2NzaTIiLCJMYXN0TmFtZSI6bnVsbCwiRGF0ZU9mQmlydGgiOm51bGwsIlJlZ2lzdHJhdGlvbkRhdGUiOiIyMDIzLTEyLTA4VDExOjE5OjU0LjY2M1oiLCJQcm9maWxlUGljdHVyZVVybCI6bnVsbCwiV2Vic2l0ZSI6bnVsbCwiTG9jYXRpb24iOm51bGwsIklzVmVyaWZpZWQiOmZhbHNlLCJPdHBTZWNyZXQiOm51bGwsImlhdCI6MTcwMjU3NjIzMiwiZXhwIjoxNzAyNjYyNjMyfQ.GyxcbYuXWeDem1_WMu69NRRAttcKrRUTCTgCdAfIAqg


